# Generated by Django 4.1.7 on 2023-04-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
