# Generated by Django 4.1.7 on 2023-04-17 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_test_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="bodu",
            new_name="popularity",
        ),
    ]
