# Generated by Django 4.1.7 on 2023-04-22 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_bodu_test_popularity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("UA", "Ukrainian"),
                            ("EN", "English"),
                            ("PL", "Poland"),
                        ],
                        default="UA",
                        max_length=2,
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="xxxxxx@xxxxxx",
                                regex="^\\w+(_?\\w*)*-?\\w*(_?\\w*)*@\\w+(\\.\\w*)+$",
                            )
                        ],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="the number should have the following format: +380xx xxx xx xx",
                                regex="^\\+?3?8?0?\\d{2}[ -]?(\\d[ -]?){7}$",
                            )
                        ],
                    ),
                ),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
