# Generated by Django 4.1.7 on 2023-04-26 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_registration_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="name",
            new_name="username",
        ),
    ]
