# Generated by Django 4.1.7 on 2023-05-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_rename_piple_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="adult",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="people",
            name="gender",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="people",
            name="known_for",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="people",
            name="popularity",
            field=models.FloatField(),
        ),
    ]
