# Generated by Django 4.1.7 on 2023-05-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_people_adult_alter_people_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="people",
            name="id_my",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="people",
            name="id",
            field=models.IntegerField(),
        ),
    ]
