# Generated by Django 4.1.7 on 2023-05-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_people_id_my"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="id_my",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
