# Generated by Django 4.1.7 on 2023-05-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_people_id_my"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                ("id_my", models.IntegerField(primary_key=True, serialize=False)),
                ("adult", models.BooleanField(default=False)),
                ("backdrop_path", models.CharField(max_length=500)),
                ("genre_ids", models.JSONField()),
                ("id", models.IntegerField()),
                ("original_language", models.CharField(max_length=500)),
                ("original_title", models.CharField(max_length=500)),
                ("overview", models.CharField(max_length=500)),
                ("popularity", models.FloatField()),
                ("profile_path", models.CharField(max_length=500)),
                ("release_date", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=500)),
                ("video", models.BooleanField(default=False)),
                ("vote_average", models.FloatField()),
                ("vote_count", models.IntegerField()),
            ],
        ),
    ]
