# Generated by Django 4.1.7 on 2023-05-03 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_movies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movies",
            old_name="profile_path",
            new_name="poster_path",
        ),
    ]
