# Generated by Django 4.1.7 on 2023-05-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_rename_profile_path_movies_poster_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="created",
        ),
        migrations.RemoveField(
            model_name="test",
            name="popularity",
        ),
        migrations.RemoveField(
            model_name="test",
            name="updated",
        ),
        migrations.AlterField(
            model_name="test",
            name="title",
            field=models.JSONField(),
        ),
    ]
