# Generated by Django 4.1.7 on 2023-05-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_test_name_alter_test_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="title",
            field=models.DateTimeField(),
        ),
    ]
