# Generated by Django 4.1.7 on 2023-05-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_alter_test_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="title",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
