# Generated by Django 4.1.7 on 2023-05-24 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_alter_test_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="xxxxxx@xxxxxx",
                                regex="^\\w+(_?\\w*)*-?\\w*(_?\\w*)*@\\w+(\\.\\w*)+$",
                            )
                        ],
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("notification", models.CharField(max_length=1500)),
                ("date_request", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="Test",
            new_name="LastLogin",
        ),
    ]
