# Generated by Django 4.1.7 on 2023-05-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_notification_rename_test_lastlogin"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="name",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
